# Copyright (C) 2018-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the under the Apache License,
# Version 2.0 (the "License”); you may not use this file except in compliance with the License. You may obtain a copy
# of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# The following are necessary for building packr
required = [ "golang.org/x/sync/errgroup", "github.com/markbates/grift", "github.com/spf13/cobra" ]

[[constraint]]
  name = "code.cloudfoundry.org/cli"
  version = "6.34.1"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.10.4"


[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"
